Bug #49955: ld error message: undefined reference to `strmov_overlapp'
32bit builds with the --enable-assembler flag (enabled by default)
fail with an error message: undefined reference to `strmov_overlapp'.

Since the fix for bug 48866 we use a home-grown strmov function
instead of the ctpcpy function, but the source file for this
function was missed in the Makefile.am.

The strings/Makefile.am file has been modified to include strmov.c
file into ASSEMBLER_x86 and ASSEMBLER_sparc32 sections.

--BZR--
revision-id: gshchepa@mysql.com-20100111142122-xy9qa4jhx0dq3luh
property-branch-nick: mysql-5.0-bugteam
property-file-info: ld7:file_id64:sp1f-makefile.am-19700101030959-jfitkanzc3r4h2otoyaaprgqn7muf4ux7:message195:Bug #49955: ld error message: undefined reference to `strmov_overlapp'
property-file-info: 
property-file-info: The strings/Makefile.am file has been modified to include
property-file-info: strmov.c file into ASSEMBLER_x86 and ASSEMBLER_sparc32 sections.
property-file-info: 4:path19:strings/Makefile.amee
testament3-sha1: 20731d438535a44e8ddcfe64c9293d08a42d4b57