Fix compiler warnings about unused parameters:
mysys/my_sync.c: In function 'my_sync_dir':
mysys/my_sync.c:103:29: error: unused parameter 'dir_name'
mysys/my_sync.c:103:43: error: unused parameter 'my_flags'
mysys/my_sync.c: In function 'my_sync_dir_by_file':
mysys/my_sync.c:144:37: error: unused parameter 'file_name'
mysys/my_sync.c:144:52: error: unused parameter 'my_flags'

--BZR--
revision-id: vasil.dimov@oracle.com-20100909131548-df4vgmucy6scie3i
property-branch-nick: mysql-5.5-bugfixing
testament3-sha1: 5d713084845c900bcec5a94c1c627f94def1da2c