Bug#14862 undefined reference to `isinf' on SOLARIS - strings/strtod.c  - Change the configure test looking for 'isinf' so the value returned from isinf is used. That avoids the call to isinf being optimized away.
--BZR--
revision-id: sp1r-msvensson@shellback.(none)-20060912134748-37416
property-file-info: ld7:file_id65:sp1f-configure.in-19700101030959-mgdpoxtnh2ewmvusvfpkreuhwvffkcjw7:message90:Use the value returned from isinf so it's not optimized away by the compiler(i.e gcc 4.1)
property-file-info: 4:path12:configure.inee
property-sp1-file-info: ld9:commit_id60:msvensson@shellback.(none)|configure.in|20060912134745|393037:file_id53:BK|configure.in|19700101030959|00052|606b4ee8690d8c62ee
testament3-sha1: 6e7a4650caa25f4112851f24d999587b61532469