Fixed one warning and two errors reported by VC 6.0.
--BZR--
revision-id: sp1r-timour@mysql.com-20041118092418-46129
property-file-info: ld7:file_id59:sp1f-ignore-20001018235455-q4gxfbritt5f42nwix354ufpsvrf5ebj7:message47:Added ndb/tools/ndb_restore to the ignore list
property-file-info: 4:path20:BitKeeper/etc/ignoreed7:file_id60:sp1f-item.cc-19700101030959-u7hxqopwpfly4kf5ctlyk2dvrq4l3dhn7:message149:Fixed VC 6.0 warning:
property-file-info: mysql-5.0.2-alpha\sql\item.cpp(1729) : warning C4715: 'resolve_ref_in_select_and_group' : not all control paths return a value
property-file-info: 4:path11:sql/item.cced7:file_id65:sp1f-opt_range.cc-19700101030959-afe3wtevb7zwrg4xyibt35uamov5r7ds7:message547:Fixed VC 6.0 errors:
property-file-info: ERROR # 4: mysql-5.0.2-alpha\sql\opt_range.cpp(8070) : error C2664: 'key_cmp' : cannot convert parameter 2 from 'char *' to 'const unsigned char *'
property-file-info:         Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
property-file-info: 
property-file-info: ERROR # 5: mysql-5.0.2-alpha\sql\opt_range.cpp(8196) : error C2664: 'key_cmp' : cannot convert parameter 2 from 'char *' to 'const unsigned char *'
property-file-info:         Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast 
property-file-info: 4:path16:sql/opt_range.ccee
property-sp1-file-info: ld9:commit_id58:timour@mysql.com|BitKeeper/etc/ignore|20041118092415|247107:file_id83:sasha@mysql.sashanet.com|BitKeeper/etc/ignore|20001018235455|34248|9818ca34d1c8620aed9:commit_id49:timour@mysql.com|sql/item.cc|20041118092415|431857:file_id52:BK|sql/item.cc|19700101030959|01725|b82371a0c68be6a6ed9:commit_id54:timour@mysql.com|sql/opt_range.cc|20041118092415|432527:file_id57:BK|sql/opt_range.cc|19700101030959|01767|51b13ee9b9c66bbdee
testament3-sha1: bd9b602990c35d1cf3bdb9b1d19cd7f4b6967c9b