Fix for BUG#11755168 '46895: test "outfile_loaddata" fails (reproducible)'. In sql_class.cc, 'row_count', of type 'ha_rows', was used as last argument for ER_TRUNCATED_WRONG_VALUE_FOR_FIELD which is "Incorrect %-.32s value: '%-.128s' for column '%.192s' at row %ld". So 'ha_rows' was used as 'long'. On SPARC32 Solaris builds, 'long' is 4 bytes and 'ha_rows' is 'longlong' i.e. 8 bytes. So the printf-like code was reading only the first 4 bytes. Because the CPU is big-endian, 1LL is 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x01 so the first four bytes yield 0. So the warning message had "row 0" instead of "row 1" in test outfile_loaddata.test: -Warning	1366	Incorrect string value: '\xE1\xE2\xF7' for column 'b' at row 1 +Warning	1366	Incorrect string value: '\xE1\xE2\xF7' for column 'b' at row 0
All error-messaging functions which internally invoke some printf-life function
are potential candidate for such mistakes.
One apparently easy way to catch such mistakes is to use
ATTRIBUTE_FORMAT (from my_attribute.h).
But this works only when call site has both:
a) the format as a string literal
b) the types of arguments.
So:
  func(ER(ER_BLAH), 10);
will silently not be checked, because ER(ER_BLAH) is not known at
compile time (it is known at run-time, and depends on the chosen
language).
And
  func("%s", a va_list argument);
has the same problem, as the *real* type of arguments is not
known at this site at compile time (it's known in some caller).
Moreover,
  func(ER(ER_BLAH));
though possibly correct (if ER(ER_BLAH) has no '%' markers), will not
compile (gcc says "error: format not a string literal and no format
arguments").

Consequences:
1) ATTRIBUTE_FORMAT is here added only to functions which in practice
take "string literal" formats: "my_error_reporter" and "print_admin_msg".
2) it cannot be added to the other functions: my_error(),
push_warning_printf(), Table_check_intact::report_error(),
general_log_print().

To do a one-time check of functions listed in (2), the following
"static code analysis" has been done:
1) replace
  my_error(ER_xxx, arguments for substitution in format)
with the equivalent
  my_printf_error(ER_xxx,ER(ER_xxx), arguments for substitution in
format),
so that we have ER(ER_xxx) and the arguments *in the same call site*
2) add ATTRIBUTE_FORMAT to push_warning_printf(),
Table_check_intact::report_error(), general_log_print()
3) replace ER(xxx) with the hard-coded English text found in
errmsg.txt (like: ER(ER_UNKNOWN_ERROR) is replaced with
"Unknown error"), so that a call site has the format as string literal
4) this way, ATTRIBUTE_FORMAT can effectively do its job
5) compile, fix errors detected by ATTRIBUTE_FORMAT
6) revert steps 1-2-3.
The present patch has no compiler error when submitted again to the
static code analysis above.
It cannot catch all problems though: see Field::set_warning(), in
which a call to push_warning_printf() has a variable error
(thus, not replacable by a string literal); I checked set_warning() calls
by hand though.

See also WL 5883 for one proposal to avoid such bugs from appearing
again in the future.

The issues fixed in the patch are:
a) mismatch in types (like 'int' passed to '%ld')
b) more arguments passed than specified in the format.
This patch resolves mismatches by changing the type/number of arguments,
not by changing error messages of sql/share/errmsg.txt. The latter would be wrong,
per the following old rule: errmsg.txt must be as stable as possible; no insertions
or deletions of messages, no changes of type or number of printf-like format specifiers,
are allowed, as long as the change impacts a message already released in a GA version.
If this rule is not followed:
- Connectors, which use error message numbers, will be confused (by insertions/deletions
of messages)
- using errmsg.sys of MySQL 5.1.n with mysqld of MySQL 5.1.(n+1)
could produce wrong messages or crash; such usage can easily happen if
installing 5.1.(n+1) while /etc/my.cnf still has --language=/path/to/5.1.n/xxx;
or if copying mysqld from 5.1.(n+1) into a 5.1.n installation.
When fixing b), I have verified that the superfluous arguments were not used in the format
in the first 5.1 GA (5.1.30 'bteam@astra04-20081114162938-z8mctjp6st27uobm').
Had they been used, then passing them today, even if the message doesn't use them
anymore, would have been necessary, as explained above.
--BZR--
revision-id: guilhem.bichot@oracle.com-20110516200401-oq7x89kr4aue6g83
property-branch-nick: 5.1-2
property-file-info: ld7:file_id64:sp1f-my_getopt.h-20020125212018-wxrgonczg7uaw6w5ohby34eicbbwehct7:message97:this function pointer is used only with "string literal" formats, so we can add
property-file-info: ATTRIBUTE_FORMAT.4:path19:include/my_getopt.hed7:file_id54:default.experimental-20090224104813-e52mxw708penxv44-17:message20:test should pass now4:path43:mysql-test/collections/default.experimentaled7:file_id62:sp1f-derror.cc-19700101030959-542noqujcieu5kewg2mfhks47cvxjspq7:message79:by having a format as string literal, ATTRIBUTE_FORMAT check becomes effective.4:path13:sql/derror.cced7:file_id61:sp1f-event.cc-20051202122200-as66hughd4bhrhu2uqbb6mpogou2yihk7:message229:Change justified by the following excerpt from sql/share/errmsg.txt:
property-file-info: ER_EVENT_SAME_NAME
property-file-info:         eng "Same old and new event name"
property-file-info: ER_EVENT_SET_VAR_ERROR
property-file-info:         eng "Error during starting/stopping of the scheduler. Error code %u"4:path13:sql/events.cced7:file_id61:sp1f-field.cc-19700101030959-f4imaofclsea3n4fj4ow5m7havmyxa2r7:message333:ER_TOO_BIG_SCALE 42000 S1009
property-file-info:         eng "Too big scale %d specified for column '%-.192s'. Maximum is %lu."
property-file-info: ER_TOO_BIG_PRECISION 42000 S1009
property-file-info:         eng "Too big precision %d specified for column '%-.192s'. Maximum is %lu."
property-file-info: ER_TOO_BIG_DISPLAYWIDTH 42000 S1009
property-file-info:         eng "Display width out of range for column '%-.192s' (max = %lu)"4:path12:sql/field.cced7:file_id69:sp1f-ha_ndbcluster.cc-20040414175836-rvqnoxrkqexyhfu3d62s4t345ip7rez27:message128:ER_OUTOFMEMORY HY001 S1001
property-file-info:         eng "Out of memory; restart server and try again (needed %d bytes)"
property-file-info: (sizeof() returns size_t)4:path20:sql/ha_ndbcluster.cced7:file_id73:sp1f-ha_ndbcluster_binlog-20060112185048-3hthowbxyrrly3srxavlrufjf5mmgqm67:message108:Too many arguments for:
property-file-info: ER_GET_ERRMSG  
property-file-info:         eng "Got error %d '%-.100s' from %s"
property-file-info: Patch by Jonas Oreland.4:path27:sql/ha_ndbcluster_binlog.cced7:file_id68:sp1f-ha_partition.cc-20050718113037-eoky4qluumb5dmdyg5z6n2fvdkgutxms7:message83:print_admin_msg() is used only with a literal as format, so ATTRIBUTE_FORMAT
property-file-info: works.4:path19:sql/ha_partition.cced7:file_id63:sp1f-handler.cc-19700101030959-ta6zfrlbxzucylciyro3musjsdpocrdh7:message128:ER_OUTOFMEMORY HY001 S1001
property-file-info:         eng "Out of memory; restart server and try again (needed %d bytes)"
property-file-info: (sizeof() returns size_t)4:path14:sql/handler.cced7:file_id67:sp1f-item_create.cc-19700101030959-zdsezbi5r5xu5syntjdzqs2d2dswsojn7:message379:ER_TOO_BIG_SCALE 42000 S1009
property-file-info:         eng "Too big scale %d specified for column '%-.192s'. Maximum is %lu."
property-file-info: ER_TOO_BIG_PRECISION 42000 S1009
property-file-info:         eng "Too big precision %d specified for column '%-.192s'. Maximum is %lu."
property-file-info: 'c_len' and 'c_dec' are char*, passed as %d !! We don't know their value
property-file-info: (as strtoul() failed), but they are likely big, so we use INT_MAX.
property-file-info: 'len' is ulong.4:path18:sql/item_create.cced7:file_id65:sp1f-item_func.cc-19700101030959-3wmsx76yvc25sroqpfrx2n77kqdxxn3y7:message156:ER_WARN_DATA_OUT_OF_RANGE 22003 
property-file-info:         eng "Out of range value for column '%s' at row %ld"
property-file-info: ER_CANT_FIND_UDF  
property-file-info:         eng "Can't load function '%-.192s'"
property-file-info: 4:path16:sql/item_func.cced7:file_id68:sp1f-item_strfunc.cc-19700101030959-yl2pwnrngmla3nmlgiuiwrztx3iu4ffl7:message181:ER_TOO_BIG_FOR_UNCOMPRESS  
property-file-info:         eng "Uncompressed data size too large; the maximum size is %d (probably, length of uncompressed data was corrupted)"
property-file-info: max_allowed_packet is ulong.4:path19:sql/item_strfunc.cced7:file_id65:sp1f-mysql_priv.h-19700101030959-4fl65tqpop5zfgxaxkqotu2fa2ree5ci7:message47:sql_print_message_func is a function _pointer_.4:path16:sql/mysql_priv.hed7:file_id63:sp1f-sp_head.cc-20021208185920-jtgc5wvyqdnu2gvcdus3gazrfhxbofxd7:message166:ER_SP_RECURSION_LIMIT
property-file-info:         eng "Recursive limit %d (as set by the max_sp_recursion_depth variable) was exceeded for routine %.192s"
property-file-info: max_sp_recursion_depth is ulong4:path14:sql/sp_head.cced7:file_id63:sp1f-sql_acl.cc-19700101030959-c4hku3uqxzujthqnndeprbrhamqy6a4i7:message186:ER_PASSWORD_NO_MATCH 42000 
property-file-info:         eng "Can't find any matching row in the user table"
property-file-info: ER_CANT_CREATE_USER_WITH_GRANT 42000
property-file-info:         eng "You are not allowed to create a user with GRANT"4:path14:sql/sql_acl.cced7:file_id64:sp1f-sql_base.cc-19700101030959-w7tul2gb2n4jzayjwlslj3ybmf3uhk6a7:message200:ER_NOT_KEYFILE  
property-file-info:         eng "Incorrect key file for table '%-.200s'; try to repair it"
property-file-info: ER_TOO_MANY_TABLES  
property-file-info:         eng "Too many tables; MySQL can only use %d tables in a join"
property-file-info: MAX_TABLES is size_t.4:path15:sql/sql_base.cced7:file_id66:sp1f-sql_binlog.cc-20051222053449-o6vkdfrjkuledkjdwz2jx3zykz4izfsz7:message46:ER_UNKNOWN_ERROR  
property-file-info:         eng "Unknown error"4:path17:sql/sql_binlog.cced7:file_id65:sp1f-sql_class.cc-19700101030959-rpotnweaff2pikkozh3butrf7mv3oero7:message198:ER_TRUNCATED_WRONG_VALUE_FOR_FIELD  
property-file-info:         eng "Incorrect %-.32s value: '%-.128s' for column '%.192s' at row %ld"
property-file-info: WARN_DATA_TRUNCATED 01000 
property-file-info:         eng "Data truncated for column '%s' at row %ld"4:path16:sql/sql_class.cced7:file_id67:sp1f-sql_connect.cc-20070223111352-fhh5znxdfvzxuca7da3uu4olnwgkrm4n7:message128:ER_HANDSHAKE_ERROR 08S01 
property-file-info:         eng "Bad handshake"
property-file-info: ER_BAD_HOST_ERROR 08S01 
property-file-info:         eng "Can't get hostname for your address"4:path18:sql/sql_connect.cced7:file_id66:sp1f-sql_insert.cc-19700101030959-xgwqe5svnimxudzdcuitauljzz2zjk5g7:message98:ER_WRONG_VALUE_COUNT_ON_ROW 21S01 
property-file-info:         eng "Column count doesn't match value count at row %ld"4:path17:sql/sql_insert.cced7:file_id65:sp1f-sql_parse.cc-19700101030959-ehcre3rwhv5l3mlxqhaxg36ujenxnrcd7:message282:ER_WARN_HOSTNAME_WONT_WORK  
property-file-info:         eng "MySQL is started in --skip-name-resolve mode; you must restart it without this switch for this grant to work"
property-file-info: ER_TOO_HIGH_LEVEL_OF_NESTING_FOR_SELECT
property-file-info: 	eng "Too high level of nesting for select"
property-file-info: ER_UNKNOWN_ERROR  
property-file-info:         eng "Unknown error"4:path16:sql/sql_parse.cced7:file_id69:sp1f-sql_partition.cc-20050718113038-57h5bzswps6cel2y7k7qideue3ghbg3u7:message102:ER_OUTOFMEMORY HY001 S1001
property-file-info:         eng "Out of memory; restart server and try again (needed %d bytes)"4:path20:sql/sql_partition.cced7:file_id66:sp1f-sql_plugin.cc-20051105112032-hrm64p6xfjq33ud6zy3uivpo7azm75a27:message102:ER_OUTOFMEMORY HY001 S1001
property-file-info:         eng "Out of memory; restart server and try again (needed %d bytes)"4:path17:sql/sql_plugin.cced7:file_id67:sp1f-sql_prepare.cc-20020612210720-gtqjjiu7vpmfxb5xct2qke7urmqcabli7:message293:ER_OUTOFMEMORY HY001 S1001
property-file-info:         eng "Out of memory; restart server and try again (needed %d bytes)"
property-file-info: ER_UNKNOWN_STMT_HANDLER  
property-file-info:         eng "Unknown prepared statement handler (%.*s) given to %s"
property-file-info: length value (for '%.*s') must be 'int', per the doc of printf()
property-file-info: and the code of my_vsnprintf().4:path18:sql/sql_prepare.cced7:file_id64:sp1f-sql_show.cc-19700101030959-umlljfnpplg452h7reeyqr4xnbmlkvfj7:message102:ER_OUTOFMEMORY HY001 S1001
property-file-info:         eng "Out of memory; restart server and try again (needed %d bytes)"4:path15:sql/sql_show.cced7:file_id65:sp1f-sql_table.cc-19700101030959-tzdkvgigezpuaxnldqh3fx2h7h2ggslu7:message129:ER_TOO_BIG_FIELDLENGTH 42000 S1009
property-file-info:         eng "Column length too big for column '%-.192s' (max = %lu); use BLOB or TEXT instead"4:path16:sql/sql_table.cced7:file_id61:sp1f-table.cc-19700101030959-nsxtem2adyqzwe6nz4cgrpcmts3o54v77:message302:ER_NOT_FORM_FILE  
property-file-info:         eng "Incorrect information in file: '%-.200s'"
property-file-info: ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE
property-file-info:         eng "Column count of mysql.%s is wrong. Expected %d, found %d. Created with MySQL %d, now running %d. Please use mysql_upgrade to fix this error."
property-file-info: table->s->mysql_version is ulong.4:path12:sql/table.cced7:file_id62:sp1f-unireg.cc-19700101030959-6a4wymwak6cmvk25gch56ctjvadrhu3v7:message354:ER_TOO_LONG_TABLE_COMMENT
property-file-info:   eng "Comment for table '%-.64s' is too long (max = %lu)"
property-file-info: ER_TOO_LONG_FIELD_COMMENT
property-file-info:   eng "Comment for field '%-.64s' is too long (max = %lu)"
property-file-info: ER_TOO_BIG_ROWSIZE 42000 
property-file-info:         eng "Row size too large. The maximum row size for the used table type, not counting BLOBs, is %ld. You have to change some columns to TEXT or BLOBs"
property-file-info:  4:path13:sql/unireg.ccee
testament3-sha1: a7124cc889c1820db6a875f087f32ff4a7843995