Bug #49480: WHERE using YEAR columns returns unexpected results
A few problems were found in the fix for bug 43668:
1) Comparison of the YEAR column with NULL always returned TRUE;
2) Comparison of the YEAR column with constants always returned
   unpredictable result;
3) Unnecessary conversion warnings when comparing a non-integer
   constant with a NULL value in the YEAR column;

The problems described above have been resolved with an
exception: zero (i.e. invalid) YEAR column value comparison
with 00 or 2000 still fail (it is not a regression and it was
not a regression), so MIN/MAX on YEAR column containing zero
value still fail.

--BZR--
revision-id: gshchepa@mysql.com-20091210060544-1birwlvh7pjjqxh5
property-branch-nick: mysql-5.1-bugteam
property-file-info: ld7:file_id69:sp1f-type_year.result-20001228015634-qnsjzaaz3ams6pb2etie5s3eleghfgp57:message26:Test case for bug #49480.
property-file-info: 4:path29:mysql-test/r/type_year.resulted7:file_id67:sp1f-type_year.test-20001228015637-j547qmpytndiwdwgn35oq34jgjduzo6l7:message26:Test case for bug #49480.
property-file-info: 4:path27:mysql-test/t/type_year.tested7:file_id68:sp1f-item_cmpfunc.cc-19700101030959-hrk7pi2n6qpwxauufnkizirsoucdcx2e7:message936:- The get_year_value() function has been modified to make its
property-file-info:   return value compatible with the get_datetime_value() return
property-file-info:   value (i.e. to convert numeric values into the YYYY0000000000
property-file-info:   (YYYY-00-00 00:00:00) form.
property-file-info: 
property-file-info: - The Arg_comparator::set_cmp_func method has been modified to
property-file-info:   use the get_year_value function if get_datetime_value() is not
property-file-info:   applicable.
property-file-info:   From now only 2 cases have a special processing there:
property-file-info:   * both comparing items have MYSQL_TYPE_YEAR field type
property-file-info:           or
property-file-info:   * one item have is MYSQL_TYPE_YEAR and other one is
property-file-info:     is_datetime()-compliant.
property-file-info: 
property-file-info: - New helper function try_year_cmp_func() has been
property-file-info:   added for the better code readability to call from
property-file-info:   Arg_comparator::set_cmp_func().
property-file-info: 
property-file-info: - The Arg_comparator::compare_year method has been removed
property-file-info:   since get_year_value() is compatible with the old
property-file-info:   Arg_comparator::compare_datetime method that doesn't have
property-file-info:   problems #1-#3 (see whole patch entry commentary).
property-file-info: 4:path19:sql/item_cmpfunc.cced7:file_id67:sp1f-item_cmpfunc.h-19700101030959-pcvbjplo4e4ng7ibynfhcd6pjyem57gr7:message257:- New helper function try_year_cmp_func() has been
property-file-info:   added for the better code readability to call from
property-file-info:   Arg_comparator::set_cmp_func().
property-file-info: 
property-file-info: - Unnecessary Arg_comparator::year_as_datetime and
property-file-info:   Arg_comparator::compare_year() declarations have been
property-file-info:   removed.
property-file-info: 4:path18:sql/item_cmpfunc.hee
testament3-sha1: afdf525a3c89f179f73bbcb6b0f5191077ae4bf4