Bug #42563: Message tells me to repair table though Storage             Engine doesn't allow me to.
In case of incompatible changes between old and new table
versions, the mysqlcheck program prints error messages like
this:
  error: Table upgrade required. Please do
         "REPAIR TABLE `table_name`" to fix it!

However, InnoDB doesn't support REPAIR TABLE query, so the
message is confusing.


Error message text has been changed to:

  Table upgrade required. Please do "REPAIR TABLE `table_name`"
  or dump/reload to fix it!"

--BZR--
revision-id: gshchepa@mysql.com-20090414141915-46g26l7xbmebu7sd
property-branch-nick: mysql-5.1-bugteam
property-file-info: ld7:file_id66:sp1f-repair.result-20020901175217-bbx3pgbuq4pcl73i4n64nqm42ymdvc3b7:message34:Updated test case for bug #42563.
property-file-info: 4:path26:mysql-test/r/repair.resulted7:file_id69:sp1f-varbinary.result-20001228015635-pcxyf7w4q5jybfqyuuvfynr5uuak6p3e7:message33:Updated test case for bug #42563.4:path29:mysql-test/r/varbinary.resulted7:file_id63:sp1f-errmsg.txt-20041213212820-do5w642w224ja7ctyqhyl6iihdmpkzv57:message254:Bug #42563: Message tells me to repair table though Storage
property-file-info:             Engine doesn't allow me to.
property-file-info: 
property-file-info: The ER_TABLE_NEEDS_UPGRADE error message has been changed to:
property-file-info: 
property-file-info:   Table upgrade required. Please do "REPAIR TABLE ``%-.32s`"
property-file-info:   or dump/reload to fix it!"
property-file-info: 4:path20:sql/share/errmsg.txtee
testament3-sha1: fd41236d6e2054ca9c697be7de738c5104bd4832