BUG#13545447: RPL_ROTATE_LOGS FAILS DUE TO CONCURRENCY ISSUES IN REP. CODE
Post-push fix, broken build:
sql/rpl_master.cc:1049:70: error: converting ‘false’ to pointer type ‘bool*’ [-Werror=conversion-null]
--BZR--
revision-id: pedro.gomes@oracle.com-20130218170226-p72f3h1x6lsot3y6
property-audit-revid: pedro.gomes@oracle.com-20130218170226-nkaralhtnj9xj29l
property-branch-nick: mysql-5.1
testament3-sha1: 37c4bc0084d032046f8e65d781e69f7ffe8b6a42