Bug#14862 undefined reference to `isinf' on SOLARIS - strings/strtod.c  - Rely only on HAVE_ISINF to determine if 'isinf' can be used.
--BZR--
revision-id: sp1r-msvensson@pilot.blaudden-20070412082922-37862
property-file-info: ld7:file_id64:sp1f-my_global.h-20010915021246-4vawdgfw4vg3tuxq6mejt7lrchcnceha7:message327:The test in configure.in determines if we can use "'isinf' after
property-file-info: having inluded math.h". If the test works HAVE_ISINF will be defined
property-file-info: and isinf can be used in the code.
property-file-info: When the configure test fails it's not possible to use 'isinf' only
property-file-info: by including math.h and thus 'isinf' will be defined to never return
property-file-info: that X is inifinite.
property-file-info: 4:path19:include/my_global.hee
property-sp1-file-info: ld9:commit_id65:msvensson@pilot.blaudden|include/my_global.h|20070412082920|206257:file_id79:monty@hundin.mysql.fi|include/my_global.h|20010915021246|35260|e28622e3e3120100ee
testament3-sha1: c530e60843dcb17baefac71b513cef818580d451